project_name: archie

release:
  name_template: "Release {{.Tag}}"
  github:
    owner: superleaguegaming
    name: archie
  draft: true

before:
  hooks:
  - go mod tidy
  # - go generate ./...

builds:
- env:
  - CGO_ENABLED=0

  goos:
  - linux
  - darwin
#  - windows

  goarch:
  - amd64
  - arm64

  ldflags:
  - "-s -w"
  - "-X archie/archie.Version={{.Version}}"
  - "-X archie/archie.BuildDate={{.Date}}"
  - "-X archie/archie.ReleaseTag={{.Tag}}"
  - "-X archie/archie.CommitID={{.FullCommit}}"
  - "-X archie/archie.ShortCommitID={{.ShortCommit}}"

checksum:
  algorithm: sha256
  name_template: "SHA256SUMS"

# TODO: add signing
#signs:
#- signature: "${artifact}.asc"
#  cmd: "sh"
#  args:
#  - '-c'
#  - 'gpg --quiet --detach-sign -a ${artifact}'
#  artifacts: all

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  filters:
    exclude:
    - '^docs:'
    - '^test:'

archives:
- id: targz-archives
  name_template: '{{.ProjectName}}-{{.Tag}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
  wrap_in_directory: true
  format: tar.gz
  files:
  - README.md
  - LICENSE

nfpms:
- id: archie
  file_name_template: '{{.ProjectName}}-{{.Tag}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}'
  package_name: archie
  vendor: Super League Gaming
  homepage: https://github.com/superleaguegaming/archie
  maintainer: archie@superleague.com
  description: file copy worker
  license: GPL v3
  bindir: /usr/bin
  formats:
  - deb
  - rpm
  - apk
  overrides:
    rpm:
      replacements:
        amd64: x86_64
        arm64: aarch64



# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
