ARG image="alpine:3.16.2"
ARG version="development"

FROM $image

ARG version

LABEL version="$version"

RUN apk add --update curl lsof tini su-exec
RUN rm /var/cache/apk/*

RUN adduser -D app -s /sbin/nologin
RUN mkdir /app

COPY archie-*.apk /tmp/
RUN apk add --no-cache --allow-untrusted /tmp/archie-*.apk

RUN chown -R app:app /app/
WORKDIR /app

ENTRYPOINT ["/sbin/tini", "-g", "--"]

CMD ["su-exec", "app", "./archie"]
