ARG image="alpine:3.16.2"
ARG os="linux"
ARG arch="amd64"
ARG version="development"

FROM --platform=$os/$arch $image

ARG version

LABEL version="$version"

RUN apk add --update curl lsof tini su-exec
RUN rm /var/cache/apk/*

RUN adduser -D app -s /sbin/nologin
RUN mkdir /app

COPY ./dist/archie /app/

RUN chown -R app:app /app/
WORKDIR /app

ENTRYPOINT ["/sbin/tini", "-g", "--"]

CMD ["su-exec", "app", "./archie"]
