{{-  $shutdownWaitDuration := printf "%.0fs" .Values.archie.shutdownWait -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archie.fullname" . }}
  labels:
    {{- include "archie.labels" . | nindent 4 }}
type: Opaque
data:
  DEBUG: {{ .Values.archie.debug | toString | b64enc | quote }}
  SHUTDOWN_WAIT: {{ $shutdownWaitDuration | b64enc | quote }}
  JETSTREAM_PROVISIONING_DISABLED: {{ .Values.jetstream.provisioningDisabled | toString | b64enc | quote }}
  JETSTREAM_URL: {{ .Values.jetstream.url | b64enc | quote }}
  SKIP_LIFECYCLE_EXPIRED: {{ .Values.archie.skipLifecycleExpired | toString | b64enc | quote }}

  {{- if .Values.archie.msgTimeout }}
  MSG_TIMEOUT: {{ .Values.archie.msgTimeout | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.rootCA }}
  {{ $caPath := print "/etc/nats-cert/" .Values.jetstream.rootCA.secretName }}
  JETSTREAM_ROOT_CA: {{ $caPath | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.username }}
  JETSTREAM_USERNAME: {{ .Values.jetstream.username | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.password }}
  JETSTREAM_PASSWORD: {{ .Values.jetstream.password | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.stream }}
  JETSTREAM_STREAM: {{ .Values.jetstream.stream | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.streamReplicas }}
  JETSTREAM_STREAM_REPLICAS: {{ .Values.jetstream.streamReplicas | toString | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.streamRetention }}
  JETSTREAM_STREAM_RETENTION: {{ .Values.jetstream.streamRetention | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.streamMaxSize }}
  JETSTREAM_STREAM_MAX_SIZE: {{ .Values.jetstream.streamMaxSize | toString | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.durableConsumer }}
  JETSTREAM_DURABLE_CONSUMER: {{ .Values.jetstream.durableConsumer | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.subject }}
  JETSTREAM_SUBJECT: {{ .Values.jetstream.subject | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.maxAckPending }}
  JETSTREAM_MAX_ACK_PENDING: {{ .Values.jetstream.maxAckPending | toString | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.streamMaxAge }}
  JETSTREAM_STREAM_MAX_AGE: {{ .Values.jetstream.streamMaxAge | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.streamRepublishSubject }}
  JETSTREAM_STREAM_REPUBLISH_SUBJECT: {{ .Values.jetstream.streamRepublishSubject | b64enc | quote }}
  {{- end }}

  {{- if .Values.jetstream.batchSize }}
  JETSTREAM_BATCH_SIZE: {{ .Values.jetstream.batchSize | b64enc | quote }}
  {{- end }}

  SRC_NAME: {{ .Values.source.name | b64enc | quote }}
  SRC_BUCKET: {{ .Values.source.bucket | b64enc | quote }}
  SRC_ENDPOINT: {{ .Values.source.endpoint | b64enc | quote }}
  SRC_USE_SSL: {{ .Values.source.useSSL | toString | b64enc | quote }}

  {{- if .Values.source.accessKey }}
  SRC_ACCESS_KEY: {{ .Values.source.accessKey | b64enc | quote }}
  {{- end }}

  {{- if .Values.source.secretAccessKey }}
  SRC_SECRET_ACCESS_KEY: {{ .Values.source.secretAccessKey | b64enc | quote }}
  {{- end }}

  DEST_NAME: {{ .Values.destination.name | b64enc | quote }}
  DEST_BUCKET: {{ .Values.destination.bucket | b64enc | quote }}
  DEST_ENDPOINT: {{ .Values.destination.endpoint | b64enc | quote }}
  DEST_USE_SSL: {{ .Values.destination.useSSL | toString | b64enc | quote }}
  DEST_THREADS: {{ .Values.destination.threads | toString | b64enc | quote }}
  DEST_PART_SIZE: {{ .Values.destination.partSize | toString | b64enc | quote }}

  {{- if .Values.destination.accessKey }}
  DEST_ACCESS_KEY: {{ .Values.destination.accessKey | b64enc | quote }}
  {{- end }}

  {{- if .Values.destination.secretAccessKey }}
  DEST_SECRET_ACCESS_KEY: {{ .Values.destination.secretAccessKey | b64enc | quote }}
  {{- end }}

  {{- if .Values.archie.healthCheck.enabled }}
  HEALTH_CHECK_ENABLED: {{ .Values.archie.healthCheck.enabled | toString | b64enc | quote }}
  {{- end }}

  {{- if .Values.archie.healthCheck.port }}
  HEALTH_CHECK_PORT: {{ .Values.archie.healthCheck.port | toString | b64enc | quote }}
  {{- end }}

  {{- if .Values.archie.metrics.port }}
  METRICS_PORT: {{ .Values.archie.metrics.port | toString | b64enc | quote }}
  {{- end }}
