{{-  $shutdownWaitDuration := printf "%.0fs" .Values.archie.shutdownWait -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archie.fullname" . }}
  labels:
    {{- include "archie.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    apiVersion: v1

    logLevel: {{ .Values.archie.logLevel | quote }}
    shutdownWait: {{ $shutdownWaitDuration | quote }}
    skipLifecycleExpired: {{ .Values.archie.skipLifecycleExpired | toString | quote }}

    {{- if .Values.archie.msgTimeout }}
    msgTimeout: {{ .Values.archie.msgTimeout | quote }}
    {{- end }}

    excludePaths:
      {{- with .Values.archie.excludePaths.copyObject }}
      copyObject:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.archie.excludePaths.removeObject }}
      removeObject:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    src:
      name: {{ .Values.source.name | quote }}
      bucket: {{ .Values.source.bucket | quote }}
      endpoint: {{ .Values.source.endpoint | quote }}
      useSSL: {{ .Values.source.useSSL | toString | quote }}

      {{- if .Values.source.accessKey }}
      accessKey: {{ .Values.source.accessKey | quote }}
      {{- end }}

      {{- if .Values.source.secretKey }}
      secretKey: {{ .Values.source.secretKey | quote }}
      {{- end }}


    dest:
      name: {{ .Values.destination.name | quote }}
      bucket: {{ .Values.destination.bucket | quote }}
      endpoint: {{ .Values.destination.endpoint | quote }}
      useSSL: {{ .Values.destination.useSSL | toString | quote }}
      threads: {{ .Values.destination.threads | toString | quote }}
      partSize: {{ .Values.destination.partSize | toString | quote }}

      {{- if .Values.destination.accessKey }}
      accessKey: {{ .Values.destination.accessKey | quote }}
      {{- end }}

      {{- if .Values.destination.secretKey }}
      secretKey: {{ .Values.destination.secretKey | quote }}
      {{- end }}

    jetstream:
      provisioningDisabled: {{ .Values.jetstream.provisioningDisabled | toString | quote }}
      url: {{ .Values.jetstream.url | quote }}

      {{- if .Values.jetstream.rootCA }}
      {{ $caPath := print "/etc/nats-cert/" .Values.jetstream.rootCA.secretName }}
      rootCA: {{ $caPath | quote }}
      {{- end }}

      {{- if .Values.jetstream.username }}
      username: {{ .Values.jetstream.username | quote }}
      {{- end }}

      {{- if .Values.jetstream.password }}
      password: {{ .Values.jetstream.password | quote }}
      {{- end }}

      {{- if .Values.jetstream.subject }}
      subject: {{ .Values.jetstream.subject | quote }}
      {{- end }}

      {{- if .Values.jetstream.batchSize }}
      batchSize: {{ .Values.jetstream.batchSize | quote }}
      {{- end }}

      stream:
        {{- if .Values.jetstream.stream.name }}
        name: {{ .Values.jetstream.stream.name | quote }}
        {{- end }}

        {{- if .Values.jetstream.stream.replicas }}
        replicas: {{ .Values.jetstream.stream.replicas | toString | quote }}
        {{- end }}

        {{- if .Values.jetstream.stream.retention }}
        retention: {{ .Values.jetstream.stream.retention | quote }}
        {{- end }}

        {{- if .Values.jetstream.stream.maxSize }}
        maxSize: {{ .Values.jetstream.stream.maxSize | toString | quote }}
        {{- end }}

        {{- if .Values.jetstream.stream.maxAge }}
        maxAge: {{ .Values.jetstream.stream.maxAge | quote }}
        {{- end }}

        {{- if .Values.jetstream.stream.republishSubject }}
        republishSubject: {{ .Values.jetstream.streamRepublishSubject | quote }}
        {{- end }}

      consumer:
        {{- if .Values.jetstream.consumer.name }}
        name: {{ .Values.jetstream.consumer.name | quote }}
        {{- end }}

        {{- if .Values.jetstream.consumer.maxAckPending }}
        maxAckPending: {{ .Values.jetstream.consumer.maxAckPending | toString | quote }}
        {{- end }}

    healthCheck:
      disabled: {{ eq .Values.archie.healthCheck.enabled false | toString | quote }}
      port: {{ .Values.archie.healthCheck.port | toString | quote }}

    metrics:
      port: {{ .Values.archie.metrics.port | toString | quote }}
