{{-  $shutdownWaitDuration := printf "%.0fs" .Values.archie.shutdownWait -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archie.fullname" . }}
  labels:
    {{- include "archie.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    apiVersion: v1

    logLevel: {{ .Values.archie.logLevel }}
    shutdownWait: {{ $shutdownWaitDuration }}
    skipLifecycleExpired: {{ .Values.archie.skipLifecycleExpired }}

    {{- if .Values.archie.msgTimeout }}
    msgTimeout: {{ .Values.archie.msgTimeout }}
    {{- end }}

    excludePaths:
      {{- with .Values.archie.excludePaths.copyObject }}
      copyObject:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.archie.excludePaths.removeObject }}
      removeObject:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    src:
      name: {{ .Values.source.name }}
      bucket: {{ .Values.source.bucket }}
      endpoint: {{ .Values.source.endpoint }}
      useSSL: {{ .Values.source.useSSL }}

      {{- if .Values.source.accessKey }}
      accessKey: {{ .Values.source.accessKey }}
      {{- end }}

      {{- if .Values.source.secretKey }}
      secretKey: {{ .Values.source.secretKey }}
      {{- end }}

    dest:
      name: {{ .Values.destination.name }}
      bucket: {{ .Values.destination.bucket }}
      endpoint: {{ .Values.destination.endpoint }}
      useSSL: {{ .Values.destination.useSSL }}
      threads: {{ .Values.destination.threads }}
      partSize: {{ .Values.destination.partSize }}

      {{- if .Values.destination.accessKey }}
      accessKey: {{ .Values.destination.accessKey }}
      {{- end }}

      {{- if .Values.destination.secretKey }}
      secretKey: {{ .Values.destination.secretKey }}
      {{- end }}

    jetstream:
      provisioningDisabled: {{ .Values.jetstream.provisioningDisabled }}
      url: {{ .Values.jetstream.url }}

      {{- if .Values.jetstream.rootCA }}
      {{ $caPath := print "/etc/nats-cert/" .Values.jetstream.rootCA.secretName }}
      rootCA: {{ $caPath }}
      {{- end }}

      {{- if .Values.jetstream.username }}
      username: {{ .Values.jetstream.username }}
      {{- end }}

      {{- if .Values.jetstream.password }}
      password: {{ .Values.jetstream.password }}
      {{- end }}

      {{- if .Values.jetstream.subject }}
      subject: {{ .Values.jetstream.subject }}
      {{- end }}

      {{- if .Values.jetstream.batchSize }}
      batchSize: {{ .Values.jetstream.batchSize }}
      {{- end }}

      stream:
        {{- if .Values.jetstream.stream.name }}
        name: {{ .Values.jetstream.stream.name }}
        {{- end }}

        {{- if .Values.jetstream.stream.replicas }}
        replicas: {{ .Values.jetstream.stream.replicas }}
        {{- end }}

        {{- if .Values.jetstream.stream.retention }}
        retention: {{ .Values.jetstream.stream.retention }}
        {{- end }}

        {{- if .Values.jetstream.stream.maxSize }}
        maxSize: {{ .Values.jetstream.stream.maxSize }}
        {{- end }}

        {{- if .Values.jetstream.stream.maxAge }}
        maxAge: {{ .Values.jetstream.stream.maxAge }}
        {{- end }}

        {{- if .Values.jetstream.stream.republishSubject }}
        republishSubject: {{ .Values.jetstream.streamRepublishSubject }}
        {{- end }}

      consumer:
        {{- if .Values.jetstream.consumer.name }}
        name: {{ .Values.jetstream.consumer.name }}
        {{- end }}

        {{- if .Values.jetstream.consumer.maxAckPending }}
        maxAckPending: {{ .Values.jetstream.consumer.maxAckPending }}
        {{- end }}

    healthCheck:
      disabled: {{ eq .Values.archie.healthCheck.enabled false }}
      port: {{ .Values.archie.healthCheck.port }}

    metrics:
      port: {{ .Values.archie.metrics.port }}
