apiVersion: v1
kind: Service
metadata:
  name: {{ include "archie.fullname" . }}
  labels:
    {{- include "archie.labels" . | nindent 4 }}
spec:
  type: {{ .Values.archie.service.type }}
  ports:
    - port: {{ .Values.archie.metrics.port }}
      targetPort: {{ .Values.archie.metrics.port }}
      protocol: TCP
      name: metrics
  selector:
    {{- include "archie.selectorLabels" . | nindent 4 }}
